language: php
php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

services:
  - mysql

before_script:
    - mysql -e "create database symfony;"
    - composer install
    - php bin/console doctrine:schema:create --env=test