<?php

namespace AppBundle\Repository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends \Doctrine\ORM\EntityRepository
{
}
